# Generated by Django 4.2.7 on 2023-11-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoBD',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoPM',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('asistencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignauras',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('seccion', models.CharField(max_length=10)),
                ('sala', models.CharField(max_length=6)),
            ],
        ),
    ]
