# Generated by Django 4.2.1 on 2023-10-20 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idCarrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rutProfesor', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombreProfesor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('idSala', models.IntegerField(primary_key=True, serialize=False)),
                ('Sala', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('idSeccion', models.IntegerField(primary_key=True, serialize=False)),
                ('Seccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCurso', models.CharField(max_length=60)),
                ('Sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
                ('Seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rutAlumno', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombreAlumno', models.CharField(max_length=100)),
                ('nombreCarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera')),
            ],
        ),
    ]
